application: wpi-majortracking
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /libs
  static_dir: libs

- url: /images
  static_dir: images

- url: /signup
  script: WPIMajorTracking.app
  secure: always

- url: /login
  script: WPIMajorTracking.app
  secure: always

- url: /forgot
  script: WPIMajorTracking.app
  secure: always

- url: .*
  script: WPIMajorTracking.app


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
- name: jinja2
  version: latest